apiVersion: apps/v1
kind: Deployment
metadata:
  name: github-proxy-deploy
  labels:
    app: github-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: github-proxy
  template:
    metadata:
      labels:
        app: github-proxy
    spec:
      containers:
      - name: github-proxy-microservice
        image: sigursoft/github-proxy-microservice:2.0
        ports:
        - name: undertow
          containerPort: 8080
        readinessProbe:
          tcpSocket:
            port: github-proxy
          initialDelaySeconds: 3
          periodSeconds: 2
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /
            port: undertow
          initialDelaySeconds: 6
        resources:
          limits:
            cpu: "2"
            memory: 1024Mi
          requests:
            cpu: "0.6"
            memory: 512Mi
---
kind: Service
apiVersion: v1
metadata:
  labels:
    run: prod
  name: github-proxy-service
spec:
  selector:
    app: github-proxy
  ports:
  - port: 8080
    targetPort: 8080
